[default]
src = 'contracts'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    'jolt-network/=node_modules/@jolt-network/contracts',
    'openzeppelin/=node_modules/@openzeppelin/contracts',
    'realitio/=node_modules/@realitio/realitio-contracts',
    'ds-test/=lib/ds-test/src/',
]
