[profile.default]
remappings = [
    'ds-test/=lib/ds-test/src/',
    'oz/=lib/openzeppelin-contracts/contracts/',
    'oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'forge-std/=lib/forge-std/src/',
    'tests/=tests/'
]
optimizer = false
gas_reports_ignore = ["MockOracle", "MockKPIToken"]

[profile.production]
optimizer = true
via_ir = true
optimizer_runs = 1000000
evm_version = "paris"
