[default]
src = 'contracts'
test = 'tests'
out = 'artifacts'
libs = ['node_modules']
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    'ds-test/=lib/ds-test/src/',
]

[optimizer_details]
constantOptimizer = true
yul = true

[optimizer_details.yulDetails]
optimizerSteps = 'dhfoDgvulfnTUtnIf'