[profile.default]
src = 'src'
out = 'out'
test = 'tests'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'oz/=lib/openzeppelin-contracts/contracts/',
    'oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'forge-std/=lib/forge-std/src/',
    'tests/=tests/'
]
optimizer_runs = 5000000
gas_reports_ignore = ["MockOracle", "MockKPIToken"]