name: CI
on:
    pull_request:
        paths:
            - contracts/**
            - foundry.toml
            - .github/workflows/gas-diff-report.yaml
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Setup Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly
            - name: Compare gas reports
              id: gas_diff
              uses: Rubilmax/foundry-gas-diff@v3.9
              with:
                  sortOrders: desc
                  ignore: tests/**/*
            - name: Add gas diff to sticky comment
              if:
                  github.event_name == 'pull_request' || github.event_name ==
                  'pull_request_target'
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  delete: ${{!steps.gas_diff.outputs.markdown}}
                  message: ${{steps.gas_diff.outputs.markdown}}
